# Site Settings
title: The wel_ko blog &nbsp;&nbsp;| &nbsp;&nbsp;A blog about reading, writing and the like.
email: koen.wellens@hotmail.com
description: A blog where I review books, try to report on my progress as a writer and generally add other ramblings that come to mind.
baseurl: "welkoblog"
url: "https://koenwellens.github.io/"
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Koen Wellens
user_description: The nerd with a mouth.
disqus_username: disqus_T89yRUfhW2

# Social Media
# Remove the item if you don't need it
github_username: koenwellens
twitter_username: wel_ko
linkedin_username: wellenskoen
goodreads_username: 29067301

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Reading
    url: /reading/
  - title: Writing
    url: /writing/
  - title: My Rating Scale
    url: /scale/
  - title: The wel_ko Manual
    url: /manual/
  - title: Other Blogs
    url: /other-blogs/
  - title: Contact
    url: /contact/
  - title: Disclaimer
    url: /disclaimer/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
